# Generated by Django 4.0.2 on 2022-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anımals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anımals',
            name='age',
            field=models.IntegerField(null=True, unique=False),
        ),
        migrations.AddField(
            model_name='anımals',
            name='species',
            field=models.CharField(max_length=30, null=True, unique=False),
        ),
        migrations.AddField(
            model_name='anımals',
            name='type',
            field=models.CharField(max_length=30, null=True, unique=False),
        ),
        migrations.AlterField(
            model_name='anımals',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
