# Generated by Django 4.0.2 on 2022-02-20 16:25

# Occured for unique = false

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anımals', '0002_anımals_age_anımals_species_anımals_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anımals',
            name='image',
        ),
    ]
