# Generated by Django 4.0.2 on 2022-02-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
        ('anımals', '0003_remove_anımals_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='anımals',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.owners'),
        ),
    ]
